name: Deploy to itch.io

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build:itch
        
      - name: Verify asset paths and package game
        run: |
          # Check if asset paths look correct
          echo "Checking for absolute paths in index.html..."
          grep -o 'src="/[^"]*"' dist/index.html || echo "No absolute src paths found - good!"
          grep -o 'href="/[^"]*"' dist/index.html || echo "No absolute href paths found - good!"
          
          # Package the game
          cd dist
          zip -r ../generation-ship-2.zip .
          cd ..
      
      - name: Deploy to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: generation-ship-2
          ITCH_USER: ${{ secrets.ITCH_USERNAME }}
          PACKAGE: generation-ship-2.zip
          VERSION: ${{ github.sha }}